### ISSUE TITLE
Documento gestion del proyecto: Hacer el cronograma con actividades y fechas teniendo en cuenta las fases descritas, usar project o otra app

### ISSUE THREAD

**Issue by alexabaqueroc** [LeaseMatch/LeaseMatch#8]

**Comment by alexabaqueroc** [comment]
No olvidar incluir como actividad la realizacion del documento de gestion del proyecto

**Comment by jmarciglia** [comment]
Se esta trabajando con Jorge Tellez, el las actividades y los riesgos del proyecto
